import { Component, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { LucidePlus, LucideX, LucideMinus, LucideChevronUp, LucideChevronDown, LucideCheck } from '@lucide/angular';
import { environment } from '../../../../../environments/environment';

interface Task {
  title: string;
  responsibility: string;
  user: string;
}

interface TaskGroup {
  name: string;
  expanded: boolean;
  tasks: Task[];
}

@Component({
  selector: 'app-request-tasks',
  standalone: true,
  imports: [CommonModule, FormsModule, LucidePlus, LucideX, LucideMinus, LucideChevronUp, LucideChevronDown, LucideCheck],
  templateUrl: './request-tasks.component.html',
  styleUrls: ['./request-tasks.component.scss'],
})
export class RequestTasksComponent {
  
  showSuccessModal = signal(false);
  showEmailModal = signal(false);
  emailSent = signal(false);
  
  // Email form fields
  toTags = signal<string[]>(['Munish_sharma@amicusglobal.com']);
  ccTags = signal<string[]>(['Swapnil_singh@amicusglobal.com']);
  reqId = signal('MM-2024-0045');
  requestor = signal('Grace MM portal');
  submittedOn = signal('13 July 2026');
  requestType = signal('New Finished Product');
  requestTitle = signal('Curtis Bay - Silica - New Finished Product');
  customer = signal('Curtis bay - MT General');
  dueBy = signal('13 July 2026');

  emailSubject = computed(() => `${this.reqId()} — Input Required: ${this.requestTitle()}`);

  getExternalRequestSummaryUrl(reqId: string) {
    const appBaseUrl = environment.appBaseUrl.replace(/\/$/, '');
    return `${appBaseUrl}/requests/${reqId}/summary`;
  }

  emailBody = computed(() => {
    const id = this.reqId() || 'MM-2024-0045';
    const url = this.getExternalRequestSummaryUrl(id);
    const requestor = this.requestor() || 'Grace MM portal';
    const submittedOn = this.submittedOn() || '13 July 2026';
    const requestType = this.requestType() || 'New Finished Product';
    const requestTitle = this.requestTitle() || 'Curtis Bay - Silica - New Finished Product';
    const customer = this.customer() || 'Curtis bay - MT General';
    const dueBy = this.dueBy() || '13 July 2026';

    return `Dear User,\n\nThe Finished Product Request ID ${id} - '${requestTitle}' requires your input. Your input is due by ${dueBy}.\n\nThe following are the details of your task:\nData Input needed for TCO - Please enter all the fields on the form.\n\nClick here to view the request and provide your input: ${url} of the full request summary page\n\n---\n\nRequest Details -\n\nSubmitted by: Pranjal Pandey\n\nSubmitted on: ${submittedOn}\n\nRequest: ${requestType}\n\nSite: ${customer}\n\nDescription: ${requestTitle}\n\n---\n\nIf you are not the correct recipient or would want to discontinue receipt of this email notification, please contact the submitter ${requestor}.\n\n(This email was automatically generated by the GRACE MM Approval System.)\n\nRegards,\n${requestor}`;
  });
  newToEmail = signal('');
  newCcEmail = signal('');
  
  taskGroups = signal<TaskGroup[]>([
    {
      name: 'Product Management - Data Input',
      expanded: true,
      tasks: [
        { title: 'Product Mgt', responsibility: 'Product Mgt Key Assignee', user: 'Pranjal Pandey' }
      ]
    },
    {
      name: 'Trade Compliance - Data Input',
      expanded: true,
      tasks: [
        { title: 'Trade Compliance : HS Code and Licensing requirements', responsibility: 'Trade compliance', user: 'Munish Sharma' }
      ]
    },
    {
      name: 'Logistics - Data Input',
      expanded: true,
      tasks: [
        { title: 'PSS', responsibility: 'PSS Coordinators', user: 'Rahul Sharma' }
      ]
    },
    {
      name: 'Operation - Data Input',
      expanded: true,
      tasks: [
        { title: 'Safety operational/plant', responsibility: 'EHS Key Assignee', user: 'Jayehs Chauhan' },
        { title: 'Quality', responsibility: 'QC Key Assignee', user: 'Sumant Singh' }
      ]
    },
    {
      name: 'TCO - Data Input',
      expanded: true,
      tasks: [
        { title: 'Formula Annotation', responsibility: 'TCO', user: 'John Doe' }
      ]
    }
  ]);

  toggleGroup(index: number) {
    const groups = this.taskGroups();
    groups[index].expanded = !groups[index].expanded;
    this.taskGroups.set([...groups]);
  }

  removeGroup(index: number) {
    const groups = this.taskGroups();
    groups.splice(index, 1);
    this.taskGroups.set([...groups]);
  }

  moveGroupUp(index: number) {
    if (index === 0) return;
    const groups = this.taskGroups();
    [groups[index - 1], groups[index]] = [groups[index], groups[index - 1]];
    this.taskGroups.set([...groups]);
  }

  moveGroupDown(index: number) {
    const groups = this.taskGroups();
    if (index === groups.length - 1) return;
    [groups[index], groups[index + 1]] = [groups[index + 1], groups[index]];
    this.taskGroups.set([...groups]);
  }

  removeTask(groupIndex: number, taskIndex: number) {
    const groups = this.taskGroups();
    groups[groupIndex].tasks.splice(taskIndex, 1);
    this.taskGroups.set([...groups]);
  }

  updateUser(groupIndex: number, taskIndex: number, value: string) {
    const groups = this.taskGroups();
    groups[groupIndex].tasks[taskIndex].user = value;
    this.taskGroups.set([...groups]);
  }

  addToTag() {
    const email = this.newToEmail().trim();
    if (email && !this.toTags().includes(email)) {
      this.toTags.set([...this.toTags(), email]);
      this.newToEmail.set('');
    }
  }

  removeToTag(email: string) {
    this.toTags.set(this.toTags().filter(e => e !== email));
  }

  addCcTag() {
    const email = this.newCcEmail().trim();
    if (email && !this.ccTags().includes(email)) {
      this.ccTags.set([...this.ccTags(), email]);
      this.newCcEmail.set('');
    }
  }

  removeCcTag(email: string) {
    this.ccTags.set(this.ccTags().filter(e => e !== email));
  }

  addTask() {
    console.log('Add task clicked');
    // TODO: Open add task modal
  }

  saveDraft() {
    console.log('Save as draft');
  }

  previous() {
    this.router.navigate(['/requests/new/step1']);
  }

  next() {
    // Open Outlook with mailto link
    const toEmails = this.toTags().join(';');
    const ccEmails = this.ccTags().join(';');
    const subject = encodeURIComponent(this.emailSubject());
    const body = encodeURIComponent(this.emailBody());
    
    const mailtoLink = `mailto:${toEmails}?cc=${ccEmails}&subject=${subject}&body=${body}`;
    window.location.href = mailtoLink;
    
    // Show success modal immediately
    setTimeout(() => {
      this.showSuccessModal.set(true);
    }, 500);
  }
  
  closeEmailModal() {
    this.showEmailModal.set(false);
    this.emailSent.set(false);
  }
  
  sendEmail() {
    if (this.toTags().length === 0) return;
    this.emailSent.set(true);
    // Show success message for 2 seconds then close and show submit success
    setTimeout(() => {
      this.closeEmailModal();
      this.showSuccessModal.set(true);
    }, 2000);
  }

  viewRequestSummary() {
    this.showSuccessModal.set(false);
    this.router.navigate(['/requests', 'MM-2024-0045', 'summary']);
  }

  constructor(private router: Router) {}
}

