import { Component, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { LucidePlus, LucideX, LucideMinus, LucideChevronUp, LucideChevronDown, LucideCheck } from '@lucide/angular';

interface Task {
  title: string;
  responsibility: string;
  user: string;
}

interface TaskGroup {
  name: string;
  expanded: boolean;
  tasks: Task[];
}

@Component({
  selector: 'app-request-tasks',
  standalone: true,
  imports: [CommonModule, FormsModule, LucidePlus, LucideX, LucideMinus, LucideChevronUp, LucideChevronDown, LucideCheck],
  templateUrl: './request-tasks.component.html',
  styleUrls: ['./request-tasks.component.scss'],
})
export class RequestTasksComponent {
  
  showSuccessModal = signal(false);
  showEmailModal = signal(false);
  emailSent = signal(false);
  
  // Email form fields
  toTags = signal<string[]>(['rahul.verma@saintgobain.com']);
  ccTags = signal<string[]>(['anjali.mehta@saintgobain.com']);
  reqId = signal('BMOC-2024-0045');
  requestor = signal('Grace BMOC portal');
  submittedOn = signal('10 Jun 2026');
  requestType = signal('Finished Product');
  requestTitle = signal('New Waterproofing Compound WP-250');
  customer = signal('Bangalore');
  dueBy = signal('30 Jun 2026');

  emailSubject = computed(() => `${this.reqId()} — Action Required: ${this.requestTitle()}`);

  getExternalRequestSummaryUrl(reqId: string) {
    // Build a route that works on both local and deployed environments.
    const origin = typeof window !== 'undefined' ? window.location.origin : '';
    return `${origin}/requests/${reqId}/summary`;
  }

  emailBody = computed(() => {
    const id = this.reqId() || '700719';
    const url = this.getExternalRequestSummaryUrl(id);
    const requestor = this.requestor() || 'Grace BMOC portal';
    const submittedOn = this.submittedOn() || '—';
    const requestType = this.requestType() || '—';
    const requestTitle = this.requestTitle() || '—';
    const customer = this.customer() || '—';
    const dueBy = this.dueBy() || '30 Jun 2026';

    return `Dear Team,\n\nThe ${requestType} Request ID ${id} - '${requestTitle}' requires your input. Your input is due by ${dueBy}.\n\nThe following are the details of your task:\nApproval Task for Customer Returns - Please approve the request based on the details.\n\nClick here to view the request and provide your input: ${url} of the full request summary page\n\n---\n\nRequest Details -\n\nSubmitted by: ${requestor}\n\nSubmitted on: ${submittedOn}\n\nRequest: ${requestType} - ${requestTitle}\n\nCustomer: ${customer}\n\nDescription: ${requestTitle}\n\n---\n\nIf you are not the correct recipient or would want to discontinue receipt of this email notification, please contact the submitter ${requestor}.\n\n(This email was automatically generated by the GRACE BMOC Approval System.)\n\nRegards,\n${requestor}`;
  });
  newToEmail = signal('');
  newCcEmail = signal('');
  
  taskGroups = signal<TaskGroup[]>([
    {
      name: 'Product Management',
      expanded: true,
      tasks: [
        { title: 'Marketing / Product Mgt', responsibility: 'Marketing or Product Mgt Key Assignee', user: 'Pranjal Pandey' }
      ]
    },
    {
      name: 'Trade Compliance',
      expanded: true,
      tasks: [
        { title: 'Trade Compliance : HS Code and Licensing requirements', responsibility: 'Trade compliance', user: 'Munish Sharma' }
      ]
    },
    {
      name: 'Logistics',
      expanded: true,
      tasks: [
        { title: 'PSS', responsibility: 'PSS Coordinators', user: 'Rahul Sharma' }
      ]
    },
    {
      name: 'Operation',
      expanded: true,
      tasks: [
        { title: 'Safety operational/plant', responsibility: 'EHS Key Assignee', user: 'Jayehs Chauhan' },
        { title: 'Quality', responsibility: 'QC Key Assignee', user: 'Sumant Singh' }
      ]
    },
    {
      name: 'TCO',
      expanded: true,
      tasks: [
        { title: 'Formula Annotation', responsibility: 'TCO', user: 'John Doe' }
      ]
    },
    {
      name: 'Automatic ERP Integration',
      expanded: true,
      tasks: [
        { title: 'Automatic ERP Integration', responsibility: 'Requestor', user: 'Pranjal Pandey' }
      ]
    },
    {
      name: 'Final Approval',
      expanded: true,
      tasks: [
        { title: 'Overall product validation', responsibility: 'Technical Dir or R&D Mgt Key Assignee', user: 'Rahul Sharma' }
      ]
    }
  ]);

  toggleGroup(index: number) {
    const groups = this.taskGroups();
    groups[index].expanded = !groups[index].expanded;
    this.taskGroups.set([...groups]);
  }

  removeGroup(index: number) {
    const groups = this.taskGroups();
    groups.splice(index, 1);
    this.taskGroups.set([...groups]);
  }

  moveGroupUp(index: number) {
    if (index === 0) return;
    const groups = this.taskGroups();
    [groups[index - 1], groups[index]] = [groups[index], groups[index - 1]];
    this.taskGroups.set([...groups]);
  }

  moveGroupDown(index: number) {
    const groups = this.taskGroups();
    if (index === groups.length - 1) return;
    [groups[index], groups[index + 1]] = [groups[index + 1], groups[index]];
    this.taskGroups.set([...groups]);
  }

  removeTask(groupIndex: number, taskIndex: number) {
    const groups = this.taskGroups();
    groups[groupIndex].tasks.splice(taskIndex, 1);
    this.taskGroups.set([...groups]);
  }

  updateUser(groupIndex: number, taskIndex: number, value: string) {
    const groups = this.taskGroups();
    groups[groupIndex].tasks[taskIndex].user = value;
    this.taskGroups.set([...groups]);
  }

  addToTag() {
    const email = this.newToEmail().trim();
    if (email && !this.toTags().includes(email)) {
      this.toTags.set([...this.toTags(), email]);
      this.newToEmail.set('');
    }
  }

  removeToTag(email: string) {
    this.toTags.set(this.toTags().filter(e => e !== email));
  }

  addCcTag() {
    const email = this.newCcEmail().trim();
    if (email && !this.ccTags().includes(email)) {
      this.ccTags.set([...this.ccTags(), email]);
      this.newCcEmail.set('');
    }
  }

  removeCcTag(email: string) {
    this.ccTags.set(this.ccTags().filter(e => e !== email));
  }

  addTask() {
    console.log('Add task clicked');
    // TODO: Open add task modal
  }

  saveDraft() {
    console.log('Save as draft');
  }

  previous() {
    this.router.navigate(['/requests/new/step1']);
  }

  next() {
    // Open Outlook with mailto link
    const toEmails = this.toTags().join(';');
    const ccEmails = this.ccTags().join(';');
    const subject = encodeURIComponent(this.emailSubject());
    const body = encodeURIComponent(this.emailBody());
    
    const mailtoLink = `mailto:${toEmails}?cc=${ccEmails}&subject=${subject}&body=${body}`;
    window.location.href = mailtoLink;
    
    // Show success modal immediately
    setTimeout(() => {
      this.showSuccessModal.set(true);
    }, 500);
  }
  
  closeEmailModal() {
    this.showEmailModal.set(false);
    this.emailSent.set(false);
  }
  
  sendEmail() {
    if (this.toTags().length === 0) return;
    this.emailSent.set(true);
    // Show success message for 2 seconds then close and show submit success
    setTimeout(() => {
      this.closeEmailModal();
      this.showSuccessModal.set(true);
    }, 2000);
  }

  viewRequestSummary() {
    this.showSuccessModal.set(false);
    this.router.navigate(['/requests', 'BMOC-2024-0045', 'summary']);
  }

  constructor(private router: Router) {}
}
